TR.Web/Pages/HostMan/AccountPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TR.Web.Models.Models;
using TR.Web.Services.Interfaces;

namespace TR.Web
{
    public class AccountPageModel : PageModel
    {
        readonly IMeetingVariantRepo _mvRepo;
        readonly IAcceptedSlotRepo _acRepo;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public AccountPageModel(IHttpContextAccessor httpContextAccessor, IMeetingVariantRepo mvRep, IAcceptedSlotRepo acRep)
        {
            _mvRepo = mvRep;
            _acRepo = acRep;
            _httpContextAccessor = httpContextAccessor;
        }

        public IEnumerable<MeetingVariant> MeetingVariants { get; set; }
        public IEnumerable<AcceptedSlot> AcceptedSlots { get; set; }

        public void OnGet()
        {
            var userId = _httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);

            MeetingVariants =  _mvRepo.GetMeetingVariants(userId);
            AcceptedSlots = _acRepo.GetAllAcceptedSlots(userId);
            /*
            foreach (AcceptedSlot acS in AcceptedSlots)
            {
                acS.Slot = _slRepo.FindSlotById(acS.SlotID);
            }
            */
        }
        public async Task<IActionResult> OnPostDelete(int id)
        {
            await _mvRepo.DeleteMV(id);
            return Redirect("/HostMan/AccountPage");
        }
        public async Task<IActionResult> OnPostDetails(int id)
        {
            return Redirect("/HostMan/MeetingVariantManage/"+ id);
        }

        public async Task<IActionResult> OnPostDeleteacceptedslot(int id)
        {
            await _acRepo.DeleteSlot(id);
            return Redirect("/HostMan/AccountPage");
        }
    }
}

TR.Web/Pages/HostMan/DiapasonCreate.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TR.Web.Models.Models;
using TR.Web.Services.Interfaces;

namespace TR.Web.Pages.HostMan
{
    public class DiapasonCreateModel : PageModel
    {
        readonly IDiapasonRepo _diRepo;

        public Diapason Diapason { get; set; }
       public int CurrentID;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public DiapasonCreateModel(IHttpContextAccessor httpContextAccessor, IDiapasonRepo diRep)
        {
            _diRepo = diRep;
            _httpContextAccessor = httpContextAccessor;
        }
        public void OnGet(int id)
        {
            CurrentID = id;
        }

        public async Task<IActionResult> OnPost(int id, Diapason newDia)
        {
            var userId = _httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (newDia.StartDay != null && newDia.FinishDay != null && newDia.StartTime != null && newDia.FinishTime != null)
            {
                newDia.MeetingVariantID = id;
                newDia.User = userId;
                await _diRepo.AddDiapason(newDia);
                return Redirect("/HostMan/MeetingVariantManage/"+ id);
            }
            return Page();
        }

    }
}

TR.Web/Pages/HostMan/MeetingVariantManage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TR.Web.Models.Models;
using TR.Web.Services.Interfaces;

namespace TR.Web
{
    public class MeetingVariantManageModel : PageModel
    {
        readonly IMeetingVariantRepo _mvRepo;
        readonly IDiapasonRepo _diRepo;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public MeetingVariantManageModel(IHttpContextAccessor httpContextAccessor, IMeetingVariantRepo mvRep, IDiapasonRepo diRep)
        {
            _mvRepo = mvRep;
            _diRepo = diRep;
            _httpContextAccessor = httpContextAccessor;
        }
        
        public int CurrentID { get; set; }

        [BindProperty]
        public MeetingVariant MeetingVariant {get;set;}
        public IEnumerable<Diapason> Diapasons { get; set; }
        public bool isCreated { get; set; }

        public async Task<IActionResult> OnGet(int id)
        {

            var userId = _httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);

            CurrentID = id;
            isCreated = false;
            MeetingVariant = _mvRepo.GetMeetingVariantById(id,null);
            if(MeetingVariant != null) isCreated = true;
            if (MeetingVariant != null && userId != MeetingVariant.Owner) return Redirect("/HostMan/AccountPage");
            Diapasons = _diRepo.GetAllByMeetingId(id, userId);
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(MeetingVariant newMV)
        {
            if (MeetingVariant.Title != null && MeetingVariant.Duration != null && MeetingVariant.Description != null)
            {
                var userId = _httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);

                MeetingVariant.Owner = userId;
                if (CurrentID == null || CurrentID == 0)
                {
                    MeetingVariant = await _mvRepo.CreateMV(MeetingVariant);
                }
                else
                {
                    await _mvRepo.ChangeMV(CurrentID, MeetingVariant);
                }
                return Redirect("/HostMan/MeetingVariantManage/" + MeetingVariant.MeetingVariantID);
            }
            else
            {
                return Page();
            }

        }

        public async Task<IActionResult> OnPostBackSave(int id, MeetingVariant newMV)
        {
            if (MeetingVariant.Title != null && MeetingVariant.Duration != null && MeetingVariant.Description != null)
            {
                var userId = _httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);

                MeetingVariant.Owner = userId;
                if (id == null || id == 0)
                {
                    MeetingVariant = await _mvRepo.CreateMV(MeetingVariant);
                }
                else
                {
                    await _mvRepo.ChangeMV(id, MeetingVariant);
                }
                return Redirect("/HostMan/AccountPage");
            }
            else{
                return Page();
            }
        }

        public async Task<IActionResult> OnPostDelete(int idD, int idM)
        {
            await _diRepo.DeleteDiapason(idD);
            return Redirect("/HostMan/MeetingVariantManage/"+idM);
        }


    }
}

TR.Web/Pages/HostMan/AccountPage.cshtml
@page
@model TR.Web.AccountPageModel

@{
    ViewData["Title"] = "Troinichok Account";
}

<h1>Account</h1>

<html>
<head>
    <title>Meetings templates</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <style type="text/css">

        #layer {
            width: 100%;
            padding: 10px;
            background: #dbdbdb; /* Цвет фона */
            border-radius: 5px; /* Уголки */
            width: 215px;
        }
    </style>
    <script type="text/javascript" src="~/js/site.js"></script>
</head>
<body>
    <div style="background-color: rgba(255, 255, 255, 0.5); width: auto" class="jumbotron jumbotron-fluid" , id="layer_Accepted">
        <div>
            <h2>Meetings templates</h2>
            <a asp-page="/HostMan/MeetingVariantManage">add new</a>
        </div>
        <div style="        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(205px, 1fr));">
            @if (Model.MeetingVariants != null)
            {
                @foreach (var el in Model.MeetingVariants)
                {
                    <div style="background-color: rgba(255, 255, 255, 0.8);" class="jumbotron jumbotron-fluid" , id="layer">
                        <h4>@el.Title - @el.Duration</h4>
                        <p>@el.Description</p>
                        <!--<a class="btn btn-light" asp-page="/HostMan/MeetingVariantManage" asp-route-ID="@el.MeetingVariantID">Change</a>-->
                        <form asp-page-handler="details" method="post">
                            <input type="hidden" name="id" value="@el.MeetingVariantID" />
                            <p><button class="btn btn-light">Details</button></p>
                        </form>
                        <form asp-page-handler="delete" method="post">
                            <input type="hidden" name="id" value="@el.MeetingVariantID" />
                            <p><button class="btn btn-light">Delete</button></p>
                        </form>
                        <p><button class="btn btn-light" onclick="copyTextToClipboard(@el.MeetingVariantID)">Copy link to clipboard</button></p>
                        <p> Key: <text id="copyId" value="@el.MeetingVariantID">@el.MeetingVariantID</text> </p>
                    </div>
                }
            }
        </div>
    </div>
</body>
</html>


@if (Model.AcceptedSlots != null)
{
    <html>
    <head>
        <title>Accepted meetings</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <style type="text/css">

            #layer_Accepted {
                border-radius: 5px; /* Уголки */
                width: 1070px;
                padding: 10px;
            }

            #layer_Accepted_2 {
                padding: 10px;
                border-radius: 5px; /* Уголки */
                margin-left: 20px;
                width: 1030px;
                background-color: rgba(255, 255, 255, 0.8)
            }
        </style>
    </head>
    <body>
        <div style="background-color: rgba(255, 255, 255, 0.5); width: auto" , id="layer_Accepted">
            <div>
                <h2>Accepted meetings</h2>
            </div>
            @if (Model.MeetingVariants != null)
            {
                @foreach (var el in Model.AcceptedSlots)
                {
                    <div>
                        <div style="background-color: rgba(255, 255, 255, 0.8);" , id="layer_Accepted_2">
                            <p>Data: @el.Slot.StartSlotTime.ToString("dd/MM/yyyy")</p>
                            <p>Time: @el.Slot.StartSlotTime.ToString("H:mm") - @el.Slot.FinishSlotTime.ToString("H:mm")</p>
                            <p>Title: @el.Slot.MeetingVariant.Title</p>
                            <p>Name: @el.ClientName</p>
                            <p>Mail: @el.ClientContactMail</p>
                        </div>
                        <div>
                            <form asp-page-handler="deleteacceptedslot" method="post">
                                <input type="hidden" name="id" value="@el.AcceptedSlotID" />
                                <button class="btn btn-light">Delete</button>
                            </form>
                        </div>
                    </div>
                }
            }
        </div>

    </body>
</html>
}

TR.Web/Pages/HostMan/DiapasonCreate.cshtml
@page "{id?}"
@model TR.Web.Pages.HostMan.DiapasonCreateModel
@{
    ViewData["Title"] = "DiapasonCreate";
}

<h1>Diapason Create</h1>

<html>
<form method="post">
    <head>
        <title>Meetings templates</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <style type="text/css">

            #layer_prv {
                background-color: rgba(255, 255, 255, 0.5);
                float: left;
                height: 400px;
                padding: 10px;
                border-radius: 5px;
                margin-right: 20px;
            }
            .btn {
                border: 1.5px solid #D8D8D8;
                background-color: #EAEAEA;
                color: black;
                cursor: pointer;
            }
        </style>
        <script type="text/javascript" src="~/js/site.js"></script>
    </head>
    <body>
        <div>
            <div style="width: 400px" , id="layer_prv">
                <p style="text-align: left;">Diapason first day:</p>
                <input class="form-control" name="StartDay" asp-for="Diapason.StartDay" type="date" />
                <p></p>

                <p style="text-align: left;">Diapason last day:</p>
                <input class="form-control" name="FinishDay" asp-for="Diapason.FinishDay" type="date" />

                <p style="text-align: left;">Sessions start time:</p>
                <p style="text-align: left;"><input id="appt-time" type="time" name="StartTime" asp-for="Diapason.StartTime" /></p>

                <p style="text-align: left;">Sessions end time:</p>
                <p style="text-align: left;"><input id="appt-time" type="time" name="FinishTime" asp-for="Diapason.FinishTime" /></p>
            </div>
            <div style="width: 200px;" , id="layer_prv">
                <p style="text-align: left;"><input name="IsMonday" asp-for="Diapason.IsMonday" type="checkbox" /> <label for="scales">Monday</label></p>
                <p style="text-align: left;"><input name="IsTuesday" asp-for="Diapason.IsTuesday" type="checkbox" /> <label for="scales">Tuesday</label></p>
                <p style="text-align: left;"><input name="IsWednesday" asp-for="Diapason.IsWednesday" type="checkbox" /> <label for="scales">Wednesday</label></p>
                <p style="text-align: left;"><input name="IsThursday" asp-for="Diapason.IsThursday" type="checkbox" /> <label for="scales">Thursday</label></p>
                <p style="text-align: left;"><input name="IsFriday" asp-for="Diapason.IsFriday" type="checkbox" /> <label for="scales">Friday</label></p>
                <p style="text-align: left;"><input name="IsSaturday" asp-for="Diapason.IsSaturday" type="checkbox" /> <label for="scales">Saturday</label></p>
                <p style="text-align: left;"><input name="IsSunday" asp-for="Diapason.IsSunday" type="checkbox" /> <label for="scales">Sunday</label></p>
            </div>
        </div>
        <div>
            <a class="btn btn-light" asp-route-id="@Model.CurrentID" asp-page="/HostMan/MeetingVariantManage">Back</a>
            <button asp-page-handler="BackSave" class="btn btn-light">Back and Save</button>
            <input type="hidden" name="id" value="@Model.CurrentID" />
        </div>
    </body>
</form>
</html>

TR.Web/Pages/HostMan/MeetingVariantManage.cshtml
@page "{id?}"
@model TR.Web.MeetingVariantManageModel
@{
    ViewData["Title"] = "MeetingVariantManage";
}


<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <style type="text/css">

        #layer_MVM {
            width: 100%; /* Ширина второго слоя */
            background: #ffffff; /* Цвет фона */
            border-radius: 5px; /* Уголки */
            width: 1070px;
            background-color: rgba(255, 255, 255, 0.8);
            padding: 10px;
            margin-bottom: 10px;
        }
        .btn {
            border: 1.5px solid #D8D8D8;
            background-color: #EAEAEA;
            color: black;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <form method="post">

        <a class="btn btn-light" asp-page="/HostMan/AccountPage">Back</a>
        <button asp-page-handler="BackSave" class="btn btn-light">Back and Save</button>
        <input type="hidden" name="id" value="@Model.CurrentID" />

        <!--<div asp-validation-summary="All"></div>-->
        <div id="layer_MVM">
            <div class="form-group">
                <label asp-for="@Model.MeetingVariant.Title" class="control-label"></label>
                <input asp-for="@Model.MeetingVariant.Title" value="@( Model.MeetingVariant != null ? Model.MeetingVariant.Title : "Title") ">
                <span asp-validation-for="@Model.MeetingVariant.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.MeetingVariant.Duration" class="control-label"></label>
                <input asp-for="@Model.MeetingVariant.Duration" step="60000‬"  min="00:05" max= "11:00" type="time" value="@( Model.MeetingVariant != null ? Model.MeetingVariant.Duration.ToString() : string.Empty)">
                <span asp-validation-for="@Model.MeetingVariant.Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.MeetingVariant.Description" class="control-label"></label>
                <textarea asp-for="@Model.MeetingVariant.Description" rows="7" style="width:100%;overflow:hidden;resize: none;">@( Model.MeetingVariant != null ? Model.MeetingVariant.Description : "Description")</textarea>
                <span asp-validation-for="@Model.MeetingVariant.Description" class="text-danger"></span>
            </div>
        </div>
            @if (!Model.isCreated)
            {
                <input type="submit" value="Save before continue" class="btn btn-light" />
            }
    </form>
</body>
</html>


<html>
@if (Model.isCreated)
{
    <div>
        <div>
            Diapasons
            <a asp-page="/HostMan/DiapasonCreate" asp-route-ID="@Model.CurrentID">add new</a>
        </div>
        <div>
            @if (Model.Diapasons != null)
            {
                foreach (var diap in Model.Diapasons)
                {
                    <div class="jumbotron jumbotron-fluid" , id="layer_MVM">
                        <div>
                            Dates from @diap.StartDay.ToString("dd/MM/yyyy")
                            to @diap.FinishDay.ToString("dd/MM/yyyy")
                        </div>
                        <div>
                            Sessions starts at @diap.StartTime.ToString("H:mm")
                            Ends at @diap.FinishTime.ToString("H:mm")
                        </div>
                        <div>
                            At days :
                            @if (diap.IsMonday)
                            {
                                <text> Moday</text>
                            }
                            @if (diap.IsTuesday)
                            {
                                <text> Tuesday</text>
                            }
                            @if (diap.IsWednesday)
                            {
                                <text> Wednesday</text>
                            }
                            @if (diap.IsThursday)
                            {
                                <text> Thursday</text>
                            }
                            @if (diap.IsFriday)
                            {
                                <text> Friday</text>
                            }
                            @if (diap.IsSaturday)
                            {
                                <text> Saturday</text>
                            }
                            @if (diap.IsSunday)
                            {
                                <text> Sunday</text>
                            }
                        </div>

                    </div>
                    <form method="post">
                        <button asp-page-handler="Delete" class="btn btn-light">Delete</button>
                        <input type="hidden" name="idD" value="@diap.DiapasonID" />
                        <input type="hidden" name="idM" value="@Model.MeetingVariant.MeetingVariantID" />
                    </form>
                }
            }
        </div>
    </div>


}
</html>